### PR TITLE
Handle permission errors and stale file errors better

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/6 
Ref https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/5

### CODE REVIEW

**Comment by yuvipanda** [comment]
This is actually not *quite* right, as it just ignores an entire subtree the first time *any* errors are noticed.

**Review by consideRatio — APPROVED** [review]
This is an incremental improvement as long as we don't loose track of the need to iterate on this based on `[...] it just ignores an entire subtree the first time any errors are noticed`. I opened https://github.com/yuvipanda/prometheus-dirsize-exporter/issues/10 for this for now as I couldn't come up with a quick resolution.

Title suggestion: `Handle permission errors and stale file errors better`

**Comment by consideRatio** [comment]
Thank you for working this @yuvipanda!!! :heart: :tada:

**Comment by consideRatio** [comment]
@yuvipanda let's go for a merge here and flush this incremental improvement

**Comment by yuvipanda** [comment]
Yeah, I've changed the 'fixes' to 'ref' and merged this for now, even though it's going in the wrong direction for error handling.

**Pull request merged**
